### ISSUE TITLE
荣誉文凭定义 

### ISSUE THREAD

**Issue by ieduer** [pkuschool/Honours-programs#1]
荣誉文凭定义
文凭/荣誉文凭/与普通文凭的关系
为什么是上述，我们的考量是……

**Comment by yixin-lin** [comment]
为符合培养目标、两年间获得自我成长、为学校或社会做出一定贡献力的学生设立的一项荣誉奖项。

**Comment by ieduer** [comment]
转王子乐同学

荣誉文凭定义：
我认为荣誉文凭是凌驾于普通文凭之上证书，是学校所能给予毕业生的最高认可。如果普通文凭获得者代表着具备一个北大附中毕业生的基本水平，则荣誉文凭获得者就代表着北大附中所有毕业生所具有的最高水准。而因为这是北大附中荣誉文凭，在这个证书中应当体现北大附中所特有的教学特点，所以我认为这个最高水准应当以贴近校训为依据，也就是以个性鲜明、充满自信、敢于负责为主线，并以杰出公民为落脚点进行评审。

**Comment by ieduer** [comment]
转吴思睿同学
一、 荣誉文凭定义
对北大附中毕业生所授予的最高荣誉，同时，也代表着获得者符合北大附中培养目标，代表学校对其在校期间所做的事的肯定，包括但不限于·学院、书院、社团、社会实践活动。
理由：荣誉文凭属于学校基于培养目标对学生的认可，所以应该更加贴近培养目标。荣誉文凭应该是在学生获得普通文凭的条件下所获得的，因为荣誉文凭是学校对学生的基本认可，而荣誉文凭是学校对学生的最高认可。

**Comment by ieduer** [comment]
转李前鲲同学
荣誉文凭获得者是满足获得普通文凭的基本需求的毕业生中最能体现北大附中培养目标的一个群体，他们品德，学术，对学校的贡献以及对社会的责任心都在同届人群中出类拔萃。

**Comment by ieduer** [comment]
转崔文笛老师
荣誉文凭是颁发给北大附中优秀毕业生的一个奖项，每届荣誉文凭的获得者应能杰出诠释北大附中的培养目标和育人理念

**Comment by ieduer** [comment]
转阳嘉桐同学
我认为荣誉文凭的定义就是一个在普通文凭基础上附加的文凭，是一个对于符合北大附中培养目标的杰出学生的特殊嘉奖与认可。
