### ISSUE TITLE
荣誉文凭人数是否限定

### ISSUE THREAD

**Issue by ieduer** [pkuschool/Honours-programs#2]
是否限定
1. 如是，限定多少？为什么
2. 如否，为什么

**Comment by yixin-lin** [comment]
由于每年的学生总量不一样，所以每年不能限制同样的人数。自认为自己符合申请条件的学生均可申请，最终公布出的结果要按学校当年高二年级学生总人数的5％或10％通过比较合理。但如果在面试终审或公示环节后没有那么多符合条件的学生，也不能补选，即最终获得荣誉文凭的人数可以略少于上述比例。

**Comment by ieduer** [comment]
转王子乐同学
我认为不应当限制荣誉文凭获得者的人数。
我的理由如下：
第一，客观上，每一届同学的水平都不同，而北大附中荣誉文凭的评审标准应当是一定的，这样这个文凭才有其相对应的稳定的含金量。如果限制人数，不论是限制上限还是下限，都不能够保证每年的标准相同，例如如果假如将上限定为30人的话，有一届学生非常优秀，其中小明的综合能力（按照最终评定标准）排行35，因此落选，但是如果纵向和前一年进行比较，小明的成绩是年级前十，完全可以得到荣誉文凭。因此每年当选学生的水平就相应参差不齐，证书的含金量也因此而一直变化。

第二，荣誉文凭的评审标准应当能够激励学生变成更好的自己，而不是盲目和同学进行竞争。如果我们限制人数，同学们就会更倾向于和他人进行比较，抢占名额；反之，如果不限制人数，将这项最高的荣誉颁给每一个符合标准的学生，其实不失为一种对学生的激励，使学生更加努力的提升自己的各项能力，靠近评审的标准。

**Comment by ieduer** [comment]
转吴思睿同学
由于北大附中各届毕业生人数不太一样，本人建议将人数限制在5%作业，允许1-2人的浮动空间。

理由：

如果不限制人数，会使学校每届毕业生中的荣誉文凭获得者人数出现人数浮动，太少了会显出我们学校的学生都不积极，而多了之后文凭的含金量就降低了，无论多少，都会对学校的声誉造成影响。

如果不限制人数，评审过程会出现一些问题，分过多和过少两种情况：人数过多会导致评审过程中的工作量变大，而且是由老师主观判断是否通过。如果没有人数限制，就很难限制评分标准，而且一旦发生偏差，会导致文凭的获得者人数出现异常数字，这样，就不得不限制人数。如果人数过少，就没有评审的必要性了。（这一条逻辑比较混乱，可略过）

**Comment by ieduer** [comment]
转李前鲲同学
鉴于往届的名额，2019年荣誉文凭获得者应小于20，但不设下限。

**Comment by ieduer** [comment]
转崔文笛老师
应设置获得人数上限为当届学生总人数的5%，不设置下限。
对于设置评选人数上限，我的理由是荣誉文凭获得者应能代表每届学生的最高水平，但同时为保证评选灵活性和包容度，对于什么样的学生最符合北大附中的培养目标实际有多种诠释，除GPA门槛外不可能设置外在的标准化衡量，评审投票过程依赖主观理解，此时如果不设人数上限，可能会使荣誉文凭的含金量遭受质疑。

**Comment by ieduer** [comment]
转阳嘉桐同学
需要限定人数，人数不超过当届学生总人数的5%，但不设置人数下限。

设置人数上限的目的就是为了能够选出当届最优秀的，最符合北大附中培养目标的学生。而不设置下限的原因就是希望这个荣誉文凭的获得者宁缺毋滥，要保持它的含金量。至少在我心目中来看，荣誉文凭就是一个对北大附中学生的最高嘉奖。
