### ISSUE TITLE
积点成绩是否限制？

### ISSUE THREAD

**Issue by ieduer** [pkuschool/Honours-programs#3]
现有共识：
荣誉文凭选拔一定要符合培养目标。
要设置绩点门槛。 
绩点标准定B＋。
总绩点3.5+
[已发布内容](https://pkuschool.github.io/Honours-programs/2019/05/10/2019way/)

**Comment by yixin-lin** [comment]
让学生提供高一、高二两年每学年的平均绩点（要求≥3.5），同时对F课程进行备注说明。这是对学生本职工作的考察，学习成绩也属于一个参考系。B+我认为可以去掉，允许F

**Comment by ieduer** [comment]
转崔文笛老师
绩点是否限制？

平均绩点门槛3.5，原则上不能有F。如果有特殊情况，需要对F成绩做出解释，并在初审阶段由评审团向任课教师求证。

平均绩点3.5应该是任何学力普通的学生通过努力可以达到的成绩水平，若有极特殊情况，允许解释，但评审团不应只听一方观点，与任课教师及其他相关方求证可以保证获取真实和全面的信息。

**Comment by ieduer** [comment]
转阳嘉桐同学
我认为需要限制积点，标准是总GPA不低于3.5，没有任何F选项。申请者不符合这两个标准也可以提交申请，但需要在原本所必须提交的材料上额外增加一项对自己成绩未达标的说明，例如高一因为有家庭有重大变故导致学习状态一度不佳，但后来又通过自己的努力调整了过来。

我这么要求的理由是学习是学生在高中阶段的主要任务，所以学习成绩优异也是一种学生对自己负责的主要表现。但学习也并不是高中生活的全部，成绩好也并不是北大附中培养目标中明确写出的条目，北大附中鼓励学生成为个性鲜明的公民。因此学习成绩也不应当做为一个绝对的标准。有的同学虽然学习成绩不够好，但在其他方面有非常突出的表现，同时也品德优良，有对社会和自然的回馈，就也符合北大附中的培养目标
