### ISSUE TITLE
申请需提交什么，如何提交

### ISSUE THREAD

**Issue by ieduer** [pkuschool/Honours-programs#4]
提交什么？结构化问题/网站/sway/文章照片视频……
如何提交？/为什么提交这些？

**Comment by yixin-lin** [comment]
提交forms表单用于初审。或者有更好的提交方式？暂时没想到，各位小伙伴可以再想想。
申请条件和提交内容
1.面向高二学生
2.对学生本职工作的考察：请提供高一、高二两年每学年的平均绩点（要求≥3.5），同时对F课程进行备注说明。
3.对学生综合素质的考察：让学生对培养目标进行自我解读（你认为一个学生具体做到哪些点才是符合培养目标的？），同时提交符合培养目标要求的自证说明（请提供你认为自己符合培养目标的自证说明）。
4.两年的附中学习生活，你认为自己个人的哪些方面得到了成长，哪些方面还存在不足？对于你认为的不足之处你准备如何做？
5.请对附中的成长和发展提出建议。

**Comment by ieduer** [comment]
转李前鲲同学
材料

2018年的荣誉文凭要求申请者提交小文书和sway页面，我认为2019年也应该与去年保持一致，这样可以保证评委和申请者的工作量不超额。

关于小文书，每个申请者应基于自己理解对提出的问题做出中篇长度的论述或回答，从而评委可以从申请者的回答中评估申请者对北大附中培养目标的理解以及对学校、社会现象的思考。

Sway页面应包括申请者的社团生活，爱好，荣誉奖项，特殊经历和个人信条。根据sway评委可以断定此申请者是否对学校做出贡献，是否跟同学互帮互助、和谐相处，身心是否全面发展，是否有效地管理时间等等

**Comment by ieduer** [comment]
转崔文笛老师
初审应提交1）高一和高二包含绩点的成绩单（若有不符合评选标准的情况，附加必要的解释）；2）对结构性问题的回答；3）证明自己符合北大附中培养目标的必要辅助材料。

结构性问题可包括：

1）“北大附中致力于培养个性鲜明、充满自信、敢于负责，具有思想力、领导力、创新力的杰出公民。他们无论身在何处，都能热忱服务社会，并在其中表现出对自然的尊重和对他人的关爱。”你如何理解北大附中的培养目标？

2）你认为自己是一个什么样的人？在北大附中的两年间，你发生了什么样的成长和变化？

3）为什么你认为自己符合北大附中的培养目标？请结合自己的在校成长经历进行说明。

4）你对于北大附中未来更好的办学有什么建议？

**Comment by ieduer** [comment]
转王子乐同学
初审提交forms表单回复基本问题，过了初审后提交任何学生想要提交的东西以任何学生希望的形式。

关于初审后提交的材料，我的理由：

第一，我认为正如每个学生都个性鲜明，不同的学生有自己擅长的独特的东西，我们不应当只将目光限于sway。如果只将目光限于sway，对不善于用这款软件或者不擅长平面排版的同学很不利。同时，有些材料是sway表单所不能涵盖的。不如让每个同学提交自己想交的材料，并且不限形式，这样擅长制作视频的学生可以做视频，擅长写文章的同学可以写文章，甚至同学们还可以不采用电子的形式，上交纸质版或是实物资料。这样更能体现一个同学的特性并且让上交的材料更加生动全面，最大限度的体现一个学生的特点。

第二，因为材料的形式不同，所以我们可以从准备的材料当中看到同学对这次评审的态度，从而分析其是否具有责任感，符合荣誉文凭的评审标准。

在这里做一点补充说明：能够想到的例如视频、照片、网站等应当先定一个规格，比如视频5分钟吧以内等等。并且不论以什么样的形式，文字论述部分不要超过600字。这样比较公平，并且可以减小评审老师的工作量

**Comment by ieduer** [comment]
转阳嘉桐同学
提交的内容包括三个方面：个人基本信息，初审必答题目，以及一个全方位的个人介绍。个人介绍可以用各种形式，包括但不限于做sway，写文章，剪视频等等。提交的方式还是线上提交。制作一个forms，让同学们把这三项内容全填进去提交。

个人基本信息当中包括GPA和是否有F这两项成绩调查和申请者的姓名学号等。

初审必答题目用于深入考察申请者对于荣誉文凭项目的理解，以及对于自己本人的认识。从中考察学生的思想力、个性、对自己负责程度，以及学生自己的人生观和价值观。

个人介绍是学生对自己高中生活的一个总结，是能够方便审核者对这个学生的方方面面产生一个直观、全面的印象，同时也反映出申请者本人对于自己的反思、定位、总结，和评价。从而可以了解申请者是否符合北大附中培养目标。

**Comment by ieduer** [comment]
本周例会核心主题：
1、[申请表](https://forms.office.com/Pages/DesignPage.aspx?fragment=FormId%3DdvGcSe515EmAwVKvzSjStX_OJCfvpMRDiZr_vPuTJPBUOFU1WlIzRE5VM0FaTkpSQlNPRE5HU1VQOS4u%26Token%3D279db34ee3244f2f9c41195b2a6c76b3)的设计。

2、评委构成与具体审核方式

**Comment by ieduer** [comment]
会议纪要协作平台测试 http://socrates.io/#Oav6hF6

**Comment by ieduer** [comment]
https://pkuschool.github.io/Honours-programs/2019/05/24/keyissue/
